### PR TITLE
setup_cmake for my laptop; MAKEGRID dep in VMEC?

### PR DESCRIPTION
**Pull request by jonathanschilling**
I added an entry to `setup_cmake` for my laptop running Arch Linux. All required libraries were found and the tests executed fine.
I needed to specify `-fallow-argument-mismatch` to be able to build `LIBSTELL`; `ezcdf*` is one part of the code where this requirement appears.

The `CMakeLists.txt` in the root folder lists `MAKEGRID` as a dependency for `VMEC`.
Is this indented to have `MAKEGRID` be re-built every time someone changes something in `LIBSTELL` which might also affect `MAKEGRID` or could this dependency be removed (or is there some other reason I missed out completely)?

Please don't delete this branch when merging so that I can keep adding things to it.

### CODE REVIEW

**Comment by cianciosa** [comment]
MAKEGRID is a tool needed by users of VMEC to run free boundary equilibria since it generates Vacuum fields. The build system is very fine grained. It will only rebuild MAKEGRID sources when a module that an individual MAKEGRID source file depends on changed. Otherwise it just relinks the new libstell library.

On Oct 29, 2020, at 4:42 PM, Jonathan Schilling <notifications@github.com<mailto:notifications@github.com>> wrote:


I added an entry to setup_cmake for my laptop running Arch Linux. All required libraries were found and the tests executed fine.
I needed to specify -fallow-argument-mismatch to be able to build LIBSTELL; ezcdf* is one part of the code where this requirement appears.

The CMakeLists.txt in the root folder lists MAKEGRID as a dependency for VMEC.
Is this indented to have MAKEGRID be re-built every time someone changes something in LIBSTELL which might also affect MAKEGRID or could this dependency be removed (or is there some other reason I missed out completely)?

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/ORNL-Fusion/Stellarator-Tools/pull/10

Commit Summary

  *   VMEC does not actually depend on MAKEGRID to be built --> remove dep from CMakeLists.txt
  *   'v3fit suite' --> 'stellarator tools'; added config for my laptop

File Changes

  *   M CMakeLists.txt<https://github.com/ORNL-Fusion/Stellarator-Tools/pull/10/files#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20a> (1)
  *   M setup_cmake<https://github.com/ORNL-Fusion/Stellarator-Tools/pull/10/files#diff-07d7981eef5a4b5eaebb47c709860aa2d9fc821f97ee7a4b8ac26bb81a0a5d50> (15)

Patch Links:

  *   https://github.com/ORNL-Fusion/Stellarator-Tools/pull/10.patch
  *   https://github.com/ORNL-Fusion/Stellarator-Tools/pull/10.diff

**Comment by jonathanschilling** [comment]
Thanks for the clarification.
`MAKEGRID` and `VMEC` are independent executables however and I raised above concern to reduce side effects (e.g. of breaking a compiled `VMEC` executable when working on `MAKEGRID` or the other way around).

**Comment by cianciosa** [comment]
VMEC doesn’t have any source dependency on MAKEGRID so there’s no scenario where we need to worry about that. The only think can break is the MGRIDFILE file format. But the VMEC unit tests will have coverage for that scenario. One test would will to generate vacuum fields based on a coil set and test that VMEC solved an equilibrium given those fields.

On Nov 4, 2020, at 10:46 AM, Jonathan Schilling <notifications@github.com<mailto:notifications@github.com>> wrote:



Thanks for the clarification.
MAKEGRID and VMEC are independent executables however and I raised above concern to reduce side effects (e.g. of breaking a compiled VMEC executable when working on MAKEGRID or the other way around).

**Comment by jonathanschilling** [comment]
Okay, I got it now and I will revert `setup_cmake` accordingly then.

**Comment by cianciosa** [comment]
I also noticed one last issue, can you also reset the repo tag from master_dev to master?

**Comment by jonathanschilling** [comment]
> I also noticed one last issue, can you also reset the repo tag from master_dev to master?

Sure, done.

**Review by cianciosa — APPROVED** [review]

**Pull request merged**
